# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-orderhub-api-angie

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-orderhub-api-angie'
          slot-name: 'Production'
          package: ./src/api
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B60ADBC6051D423A9FAFEE269A8C7D81 }}